version: '2'
services:
  api:
    build: ../cws-parent-portal-api
    ports:
      - "8081:8080"
    volumes:
    - ../cws-parent-portal-api/log:/var/log/cws-parent-portal-api
    - ../cws-parent-portal-api/build/libs/parentportal-all.jar:/usr/local/share/java/cws-parent-portal-api/cws-parent-portal-api.jar
    - ../cws-parent-portal-api/config/parentportal_config.yml:/usr/local/etc/cws-parent-portal-api/cws-parent-portal-api.yml
    environment:
      - DB_USER=cpp
      - DB_PASSWORD=ZQ6Y7TdsK
      - DB_JDBC_URL=jdbc:postgresql://cws-parent-portal.clb72r92gq7s.us-west-2.rds.amazonaws.com/cpp
  ui:
    build: ../cws-parent-portal-ui
    ports:
    - "8080:8080"
    volumes:
    - ../cws-parent-portal-ui/log:/var/log/cws-parent-portal-ui
    - ../cws-parent-portal-ui/src:/usr/local/share/cws-parent-portal-ui
    - ../cws-parent-portal-ui/nginx.conf:/usr/local/etc/cws-parent-portal-ui/nginx.conf
